### ISSUE TITLE
Consider ISoffitLoader implementing SpringFramework's Ordered

### ISSUE THREAD

**Issue by apetro** [drewwills/Soffit#10]
```
    /**
     * Determines the place this bean occupies in a sequence involving multiple
     * {@link ISoffitLoader} objects.  Lower-order beans are invoked
     * before higher-order beans.
     */
    int getOrder();
```

reminds of [`org.springframework.core.ordered`](http://docs.spring.io/spring/docs/current/javadoc-api/org/springframework/core/Ordered.html).

**Comment by drewwills** [comment]
I wish that type came with a pre-baked implementation of `Comparable` based on the `getOrder` method.

**Comment by drewwills** [comment]
done.

**Comment by apetro** [comment]
wrt cleaner implementation of `Comparable`, delegate to [`OrderComparator`](http://docs.spring.io/spring/docs/current/javadoc-api/org/springframework/core/OrderComparator.html)?
