### ISSUE TITLE
Proposal: Decouple Soffit request from PortletRequest implementation details

### ISSUE THREAD

**Issue by andrewstuart** [drewwills/Soffit#6]
In short: I propose including the original HTTP request as a string (e.g. `GET / HTTP/1.1\nUser-Agent:` etc.), and the portal/portlet-specific context as a separate object. I think we should try to provide a shallower abstraction that may include the portlet request, but is informed by it rather than bound to it.

As it stands now, many of the implementation details of a portlet request are visible in the abstraction we're creating. Understandably so for simplicity's sake, but it will be worthwhile to at least consider making this a low-overhead version of a portlet request, rather than adding to it.

For one example, in order to find headers from the original HTTP request, one has to know (or assume) a bit about how the portlet request properties work, as that's where (from what I can tell) the headers are kept in the PortletRequest.

Additionally, in the current model spec (as of commit 4cdbdc0eff44e2a29c984c9f674d75c429eba772), request details (scheme, serverName, serverPort) are mingled with portlet-specific details (namespace, mode, windowState, etc.).  I think to gain adoption, we should make sure we properly segregate concerns here.

I'd go as far as suggesting that we include the entire original HTTP request, in its full [RFC 7230](https://tools.ietf.org/html/rfc7230) serial text format. Every language today can properly parse an HTTP request, and I think this is an appropriate way to properly allow providers very clearly distinguished access to both the original HTTP request (often a better indication of user intent) and the portlet-specific requirements (providing system context).

Including the original request in a long-standardized serial format has the benefit of being blatantly obvious and requiring no extra cleverness to decipher. Simply point your language's HTTP parser at the "originalRequest" (or similar) string and you'll be given in return a very language-context-appropriate representation of the original request.
## Pros:
- Provide an abstraction that is more easily understood and consumed by newcomers, and does not require (much) prior knowledge of the portal/portlet architecture
- Implementation details would be primarily based on IETF standards, and supplemented with portal-specific structured data as needed for the portal use case (content aggregation and page sharing)
  - By relying on IETF standards, more developers and content providers are freed up to provide portal content in their language or framework of choice, provided they can meet an exceedingly minimum cost of entry: stay inside your namespace
- By separating the original HTTP request from the PortletRequest decorations, greater clarity is expressed to providers about the state of the system and the individual request.
## Cons:
- Unparsed HTTP request adds an element of complexity for direct consumption. Language-specific providers would need to deal with deserializing the HTTP request into a format familiar to the developers of the provider.

**Comment by drewwills** [comment]
@andrewstuart -- Are you in the office this week?  I'd like to step through this item with you.

**Comment by andrewstuart** [comment]
I'm not, unfortunately. My wife just gave birth to our daughter so I'm out for two weeks. The issue is probably the easiest place to let the community chime in anyway, though.

**Comment by drewwills** [comment]
Congrats @andrewstuart!

**Comment by drewwills** [comment]
## Update

This proposal -- together with some new ideas -- is (essentially) being implemented here:  https://github.com/drewwills/Soffit/pull/20

**Comment by drewwills** [comment]
@andrewstuart -- The changes we discussed in the Data Model Summit are merged.  (Frankly, there may be a few more before we're finished.)  I'm going to close this ticket because we agree.

**Comment by andrewstuart** [comment]
Sounds good to me. :smile:
