### ISSUE TITLE
SoffitConnector does not include Server Name Indication (SNI) for HTTPS backends

### ISSUE THREAD

**Issue by andrewstuart** [drewwills/Soffit#9]
SNI is an incredibly useful (and necessary) extension of TLS in which the TLS client, during the handshake, indicates the DNS name of the server it intends to connect to. This prevents using a TLS load balancer in front of HTTPS backend services, as well as some more modern certificate automation frameworks from being able to present (and potentially obtain) the correct certificate unless a 1:1 mapping of common_name:IP is maintained.

I've googled a bit and supposedly this shouldn't be an issue as of Java 7, but it still seems that SNI is not being used when the HTTPS connection is opened.

**Comment by drewwills** [comment]
Thanks for this ticket @andrewstuart.

**Comment by drewwills** [comment]
Looks like httpclient 4.5.2 should support SNI:  http://stackoverflow.com/questions/32341729/apache-http-client-defaults-dont-work-with-sni

I'm not sure what's interfering.

**Comment by andrewstuart** [comment]
I'll have to see if I can whip up a test case. It may be that there's another problem somewhere else in the TLS  handshake.

**Comment by andrewstuart** [comment]
So for some unrelated reason, I was looking at my environment variables and noticed that SNI was disabled through a java option. I'm testing right now to double check it's fixed, but I think that was almost certainly the reason.
